{"name": "test_login_with_invalid_credentials", "status": "passed", "start": 1700029355421, "stop": 1700029356891, "uuid": "41e82e07-497f-460d-81a6-b371994745be", "historyId": "2628823e04ad24cee2f8a49649004858", "testCaseId": "2628823e04ad24cee2f8a49649004858", "fullName": "tests.test_login.TestLogin#test_login_with_invalid_credentials", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "awaisahmad-latitude-5490"}, {"name": "thread", "value": "147189-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}